# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/RSICV/RSICV.cache/wt [current_project]
set_property parent.project_path G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/RSICV/RSICV.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/RSICV/RSICV.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/ALU.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/ALU_control.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/Add.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/Control.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/EX.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/EX_MEM.V
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/Forwarding_unit.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/Hazard_dete.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/ID.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/ID_EX.V
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/IF_ID.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/ImmGen.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/MEM_WB.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/MUX.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/PC.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/PC_TOP.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/Registers.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/WB.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/data_mem.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/inst_mem.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/riscv.v
  G:/OneDrive/Desktop/Design_Verilog/project/2050285ÎâÖÂÔ¶RISCVÆÚÄ©¿ÎÉè/prj/rtl/RISCV_SOC.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RISCV_SOC -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISCV_SOC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISCV_SOC_utilization_synth.rpt -pb RISCV_SOC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
